#!/bin/bash
wget https://sourceforge.net/projects/blue-arch-installer/files/arch-installer/Blue-Arch-Installer
losetup /dev/loop3 /root/Blue-Arch-Installer
mount /dev/loop3 /mnt
cp -R /mnt/setup /
umount /mnt
losetup -d /dev/loop3
/setup/setup
